openapi: 3.0.3
info:
  title: Ceamidia api
  description: |-
    Documentação das rotas e modelos de requisições ou respostas.
  version: "1.0"

servers:
  - url: https://apiceamidia.onrender.com
    description: servidor de produção
    variables:
      NODE_ENV:
        default: production
        description: production
      MONGO_URI:
        default: mongodb+srv://myDatabaseUser:D1fficultP%40ssw0rd@mongos0.example.com/?authSource=admin
        description: mongodb uri
      JWT_SECRET:
        default: hash
        description: hash

tags:
  - name: auth
    description: Autenicação de usuarios
  - name: crud users
    description: Autenicação de usuarios

paths:
  /login:
    post:
      tags:
        - auth
      description: autenticação de usuario.
      requestBody:
        description: JSON com dados de autenticação
        required: true
        content:
          pplication/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string

      responses:
        "200":
          description: JSON token JWT
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  x-auth-token:
                    type: string
        "401":
          description: JSON erro de autenticação
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  errorMessage:
                    type: string

  /admin:
    get:
      tags:
        - crud users
      description: mostra todos os usuarios
      responses:
        "200":
          description: JSON com todos os usuarios
          content:
            application/json:
              schema:
                type: object
                properties:
                  usuarios:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        nome:
                          type: string
                        email:
                          type: string
                        password:
                          type: string
                        role:
                          type: string
